name: CI

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  pull-requests: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release-please:
    name: Release Please
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"] # , "3.10", "3.11", "3.12", "3.13"]
        poetry-version: ["latest"] # , "main", "1.8.4"]
        os: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
